version: '3.8'

services:
  frontend:
    build:
      context: .  
      dockerfile: Dockerfile  
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}  
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
